[package]
name = "bvh"
description = "A fast BVH using SAH"
version = "0.2.2"
authors = [
    "Sven-Hendrik Haase <svenstaro@gmail.com>",
    "Alexander Dmitriev <alexander.dmitriev2580@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/svenstaro/bvh"
documentation = "https://docs.rs/crate/bvh"
keywords = ["bvh", "bounding", "volume", "sah", "aabb"]
license = "MIT"

[dependencies]
approx = "0.2"
nalgebra = "0.15.3"
rand = "0.3.14"
log = "0.3.7"

[dev-dependencies]
quickcheck = "0.4.1"
obj-rs = "0.4"

[profile.release]
lto = true

[profile.bench]
lto = true
